# vim: syntax=python tabstop=2 expandtab shiftwidth=2
# coding: utf-8

import os, re
from glob import glob

ROOT = "/mnt/lustre/scratch/home/uvi/be/hde/cd-bench"
configfile: os.path.join(ROOT, "flow", "config.json")

#REPS, SAMS = glob_wildcards("sims/{replicate}/output/bam/{sample, R\d+}.sam")
SAMPLES_TUM = sorted([
  f.split('.')[0] for f in os.listdir(os.path.join('sim', 'bam'))
    #if re.search(r'R\d+\.rc\.vcf\.gz$', f)
    if re.search(r'R\d+\.rc\.vcf\.gz$', f)
])

include: "util.smk"
include: "bcftools.smk"
#include: "bcftools_tail.smk"
include: "canopy.smk"
include: "cloe.smk"
include: "clonefinder.smk"
include: "pyclone.smk"
include: "pyclone_conn.smk"
include: "pyclone-vi.smk"
include: "pyclone-vi.cn.smk"
#include: "pyclone_tail.smk"
include: "lichee.smk"
#include: "lichee_tail.smk"
include: "pairtree.smk"
include: "phylowgs.smk"
include: "sciclone.smk"
include: "sequenza.smk"
include: "spruce.smk"
